version: "3.8"

services:
  app:
    container_name: AppFncc
    build: .
    depends_on:
      - mysqldb
    env_file:
      - ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT

  mysqldb:
    image: mysql
    container_name: DbMysql
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT